### ISSUE TITLE
Always on Top feature

### ISSUE THREAD

**Issue by muhajirframe** [elementary/photos#149]
Hi,
Is always on top feature available on elementary os photos?
I mean when i click on the other window, it doesn't overlap the `photos` window.

It will be useful for, for example when i am designing a website, and i can see my mockup with switching the browser window and photos continously.

Thank you

**Comment by danrabbit** [comment]
Right click on the headerbar and select "Always on Top" ;)

**Comment by muhajirframe** [comment]
Ups, i am sorry. I don't know if i can right click on header bar.
I thought it was not available. 
Thank you very much
