### ISSUE TITLE
The "Suggest Translation" button is pointing to the wrong link

### ISSUE THREAD

**Issue by GabrielMGitHub** [elementary/photos#151]
The "Suggest Translation" button is pointing to the wrong link. This error has several applications.
https://translations.launchpad.net/pantheon-photos

![captura de tela de 2017-05-27 14-28-07](https://cloud.githubusercontent.com/assets/8754997/26523195/b9c92570-42e8-11e7-8f2d-e7904eb7bed0.png)

**Comment by leonardo-lemos** [comment]
Solved in #145
