### ISSUE TITLE
Adjusting Date and Time makes Photos crash.

### ISSUE THREAD

**Issue by Maccer1** [elementary/photos#152]
Steps:
open a Image with right click > Open in **Photo Viewer**
right click > **Adjust Date & Time** 
set a time
click **Apply**
BOOM!
It crashed.

Doing this also changes file permissions to 755.. I'm not sure if it's related or not.

**Comment by davidmhewitt** [comment]
To add some extra information to assist with fixing the bug, this is only reproducible in the standalone viewer and it is this assertion that fails which causes the crash:

https://github.com/elementary/photos/blob/master/src/Event.vala#L471
