### ISSUE TITLE
Buttons disappearing from bottom toolbar

### ISSUE THREAD

**Issue by cristianmos** [elementary/photos#153]
The buttons are disappearing (with the exception of Play slideshow) if I go back to the Event folder (or any other folder in Library or Events) and then click on another, or the same picture. Photos needs to be restarted to get the buttons back.
![screenshot a](https://cloud.githubusercontent.com/assets/28788471/26627099/eb94b4f4-4601-11e7-9510-8912c28d613c.png)
![screenshot b](https://cloud.githubusercontent.com/assets/28788471/26627109/f3bcf98e-4601-11e7-9b61-7383a8bf9652.png)

**Comment by mcarlo95** [comment]
Same problem here with the last version of photos.

**Comment by danrabbit** [comment]
Please don't make "me too" comments. Use the :+1: reaction

**Comment by prime62** [comment]
I am having the same issue and wanted to provide additional info. 

The buttons don't disappear if the arrow keys are used to scroll through the photos. It seems to only happen when returning to the library after viewing the first photo.

Here are the error messages when running pantheon-photos from terminal:
> (pantheon-photos:6081): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
>
>(pantheon-photos:6081): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
>
>(pantheon-photos:6081): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
>[FATAL 23:08:51.744934] [Gtk] gtk_adjustment_get_lower: assertion 'GTK_IS_ADJUSTMENT (adjustment)' failed
[FATAL 23:08:51.745014] [Gtk] gtk_adjustment_set_value: assertion 'GTK_IS_ADJUSTMENT (adjustment)' failed
[FATAL 23:08:51.763440] [Gtk] gtk_adjustment_get_lower: assertion 'GTK_IS_ADJUSTMENT (adjustment)' failed
[FATAL 23:08:51.763507] [Gtk] gtk_adjustment_set_value: assertion 'GTK_IS_ADJUSTMENT (adjustment)' failed
[FATAL 23:08:51.820829] [Gtk] gtk_bin_get_child: assertion 'GTK_IS_BIN (bin)' failed
[FATAL 23:08:51.820928] [Gtk] gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed
[FATAL 23:08:51.820966] [Gtk] gtk_widget_get_style_context: assertion 'GTK_IS_WIDGET (widget)' failed
[FATAL 23:08:51.821002] [Gtk] gtk_style_context_add_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed
[FATAL 23:08:51.821036] [Gtk] gtk_button_set_relief: assertion 'GTK_IS_BUTTON (button)' failed
[FATAL 23:08:51.826105] [Gtk] gtk_widget_get_accessible: assertion 'GTK_IS_WIDGET (widget)' failed
L 6081 2017-06-05 23:08:51 [CRT] atk_object_set_name: assertion 'ATK_IS_OBJECT (accessible)' failed
[FATAL 23:08:51.826232] [Gtk] gtk_bin_get_child: assertion 'GTK_IS_BIN (bin)' failed
[FATAL 23:08:51.826320] [Gtk] gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed
[FATAL 23:08:51.826358] [Gtk] gtk_widget_get_style_context: assertion 'GTK_IS_WIDGET (widget)' failed
[FATAL 23:08:51.826410] [Gtk] gtk_style_context_add_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed
[FATAL 23:08:51.826447] [Gtk] gtk_button_set_relief: assertion 'GTK_IS_BUTTON (button)' failed
