### ISSUE TITLE
Photos is not refreshing the screen when I view multiple images

### ISSUE THREAD

**Issue by drakofrost** [elementary/photos#160]
When I use the arrow keys to view multiple images in a folder, Photos doesn't refresh the screen, the smaller images shows up on top of the bigger images, if I resize the window, the screen is updated. Gnome used to have a similar issue in the past, it was a redraw issue, the screen wasn't updated to reflect the changes, It may be the same issue here.

The issue does not appear in screenshots, so I took a picture with my smartphone. As can be seen, the bigger image is in the background.

![photos](https://user-images.githubusercontent.com/24446211/27997507-b9835c8a-64cf-11e7-8c3e-56a4bedc78be.jpg)

**Comment by cassidyjames** [comment]
Are you using elementary OS, or another distro? What GTK3 stylesheet/theme are you using (or just the default elementary one)?

**Comment by drakofrost** [comment]
I'm using Elementary OS 0.4.1, with Arc GTK theme and Papirus icon theme.
