### ISSUE TITLE
Subdirectories in ~/Pictures should implicitly be tags.

### ISSUE THREAD

**Issue by Nine-H** [elementary/photos#173]
I had a question this morning: how do I just look at my wallpapers in `~/Pictures/walls/`? I tried typing in `walls` but I got no results.

Ideally if a user has a folder like `cool_lego_robots` or `HD/4K HDR motorcycles` or `reddit-landscapes` typing substrings of those folder names should bring up those images: location is already shown in sidebar.

**Comment by danrabbit** [comment]
Photos is not a file browser. If you want to browse your photos by folder, you can use Files

**Comment by Nine-H** [comment]
maybe you've misunderstood: I don't want to browse by folder, I just want more searchable metadata.
