### ISSUE TITLE
Footbar is not visible into import view while photos are importing

### ISSUE THREAD

**Issue by artemanufrij** [elementary/photos#175]
- Import a folder
-> while photos are importing choose an event

- Select "Importing..." menu again. Footbar is't visible:
![bildschirmfoto von 2017-09-16 14 13 11](https://user-images.githubusercontent.com/16517095/30512198-fd879180-9ae9-11e7-9cad-32ec28870204.png)

**Comment by danrabbit** [comment]
Can you double check if this can be reproduced in master? It may have been solved in #184

**Comment by artemanufrij** [comment]
@danrabbit it's not solved...
