### ISSUE TITLE
Icons on in the plugins section are hard-coded.

### ISSUE THREAD

**Issue by arshubham** [elementary/photos#179]
Icons on in the plugins section are hard-coded and thus can't be used with icon themes. 
![screenshot from 2017-10-04 15-05-15](https://user-images.githubusercontent.com/14235191/31170223-f16b354a-a918-11e7-84de-8572cd001ddb.png)
![screenshot from 2017-10-04 15-05-21](https://user-images.githubusercontent.com/14235191/31170230-f4114a1e-a918-11e7-9bae-64f16253d3ed.png)

[Related issue on Papirus Icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/791)

**Comment by danrabbit** [comment]
Fixed here: https://github.com/elementary/photos/commit/2b4d62ae46106e9270a0af057196ecac089b3220

They are now named icons
