### ISSUE TITLE
Thumbnails for events are not created automatically

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/photos#231]
Photos uses some algorithm to decide which photo in an event will be chosen for the cover of that event "album". If that photo has not been viewed in the library already, and hence not had a thumbnail generated for it, the event viewer won't generate one, leaving you with a load of blank events like the below screenshot. 

![image](https://user-images.githubusercontent.com/3372394/33745869-4c4499f0-dbb1-11e7-9c8d-8785f345a21d.png)

**Comment by jeremypw** [comment]
Happens for years and months but not days
