### ISSUE TITLE
gpsig in commit made launchpad import to halt

### ISSUE THREAD

**Issue by khurshid-alam** [elementary/photos#238]
Launchpad bzr import can not handle gpg signature in commit. Remove those and rebase. See http://launchpadlibrarian.net/345259948/elementary-apps-pantheon-photos-master.log

**Comment by danrabbit** [comment]
The launchpad import needs to be migrated to git-to-git importing. We’re aware of the issue and working on migrating all of our launchpad imports :)

**Comment by khurshid-alam** [comment]
@danrabbit 

Oh. That's great. For me git based imports and recipe builds are working perfectly fine. May this can be advertised somewhere because almost all the new elementary app-devs are using bzr import for their PPAs. :(

**Comment by danrabbit** [comment]
Closing since git to git import is now set up for Photos
