### ISSUE TITLE
long tag label in sidebar is not truncated

### ISSUE THREAD

**Issue by dannios** [elementary/photos#263]
I'm getting a similar type of bug as found in [issue #1 of the mail client](https://github.com/elementary/mail/issues/1): the horizontal width of the window expands past the screen and is unable to be resized back to normal.

Seeing as both the mail client and the photo app are both former Yorba projects, they might be rooted to a similar issue?

Screenshot:
![screenshot from 2018-01-04 12 01 45](https://user-images.githubusercontent.com/35110421/34575031-44bc61b2-f147-11e7-9f8c-de71121317e1.png)

**Comment by dannios** [comment]
Closing, the photo that was auto-tagged with an absurd number of tags was deleted, fixing the problem.

**Comment by danrabbit** [comment]
I'm going to re-open this because we should probably make sure to truncate this line to avoid this issue
