### ISSUE TITLE
GExiv VAPI change causing build failure?

### ISSUE THREAD

**Issue by quequotion** [elementary/photos#264]
https://github.com/elementary/photos/blob/65512d02127fbdfe6a2149b0f546b05174eec43f/src/photos/PhotoMetadata.vala#L177
https://github.com/elementary/photos/blob/65512d02127fbdfe6a2149b0f546b05174eec43f/src/photos/PhotoMetadata.vala#L191

    /src/photos/PhotoMetadata.vala:177.9-177.22: error: The name `open_buf' does not exist in the context of `GExiv2.Metadata'
            exiv2.open_buf (buffer, length);
            ^^^^^^^^^^^^^^
    /src/pantheon-photos/src/photos/PhotoMetadata.vala:191.9-191.31: error: The name `from_app1_segment' does not exist in the context of `GExiv2.Metadata'
            exiv2.from_app1_segment (buffer, length);
            ^^^^^^^^^^^^^^^^^^^^^^^

The two were skipped by this commit, apparently to benefit Shotwell (Yorba/GNOME):
https://git.gnome.org/browse/gexiv2/commit/vapi/GExiv2-0.10.metadata?id=63b68ab3850a77b2a1acd84c7f3dd53881974df3

I tried reverting this commit and recompiling libgexiv2, but still get the same errors when compiling Photos.

Shotwell's PhotoMetadata.vala also uses them, and yet it compiles. I can't imagine why Photos does not.

https://github.com/GNOME/shotwell/blob/99c2704b1350cb074c45503578520982b5ac7e3e/src/photos/PhotoMetadata.vala#L279
https://github.com/GNOME/shotwell/blob/99c2704b1350cb074c45503578520982b5ac7e3e/src/photos/PhotoMetadata.vala#L288

**Comment by tintou** [comment]
Well, it seems that GExiv2 switched to meson and that the port causes this issue. The commit you're pointing shouldn't have happened though

**Comment by tintou** [comment]
I have proposed a patch upstream
https://bugzilla.gnome.org/show_bug.cgi?id=792431

**Comment by tintou** [comment]
now fixed in master

**Comment by quequotion** [comment]
Awesome!
