### ISSUE TITLE
"Delete" key should work in the image viewer

### ISSUE THREAD

**Issue by uncertainquark** [elementary/photos#318]
Right now, Delete key doesn't do anything when viewing an image in the image viewer. It should delete the photo (mostly with a confirmation dialog).

**Comment by peteruithoven** [comment]
Related: https://github.com/elementary/photos/issues/44

**Comment by uncertainquark** [comment]
Notably, "Delete" key also does nothing in the main Photos app while browsing with a keyboard. If app-based workflows is what is we want to be pushing, then these functions will be expected to work.

**Comment by davidak** [comment]
This would be very usefull for a keyboard based workflow.

I would like to be able to organize photos like:

1. open preview of image in files with spacebar (works, https://github.com/elementary/files/issues/438)
2. preview next image in folder with [->] (works)
3. delete files with DEL (with issue)

**Comment by cassidyjames** [comment]
This makes sense but it looks like a duplicate of #44.
