### ISSUE TITLE
[i18n]Some submenu shown as untranslated in Photos

### ISSUE THREAD

**Issue by bagjunggyu** [elementary/photos#341]
While right click the picture, below sub menu shows me as untranslated.
Adjust Date and Time...
Open In
Other Actions --> Print..., Export...

**Comment by ryonakano** [comment]
I think releasing a new version of Photos would fix this issue. Here is a screenshot which can confirm those translations works when I built the app:

![virtualbox_elementaryja_21_07_2018_19_34_46](https://user-images.githubusercontent.com/26003928/43620457-c8591b34-970d-11e8-8944-519555ab0603.png)
