### ISSUE TITLE
"Open in" offers Document Viewer for jpegs - which is unsuitable 

### ISSUE THREAD

**Issue by jeremypw** [elementary/photos#377]
The context menu item "Open In" offers the Document Viewer ('evince') as an option but choosing this results in that app refusing to open the file (its .desktop file does not include the image/jpeg mime-type).

Note that Files does not offer Document Viewer as an option for "Open In".

**Comment by ryonakano** [comment]
![Screenshot from 2019-08-15 13-38-03](https://user-images.githubusercontent.com/26003928/63074029-6dba3500-bf66-11e9-84ff-1f65157cf6a6.png)

Actually, the Document Viewer can open several image files. I checked the .desktop file of it and found that it can handle these files:

```
image/x-eps;image/x-bzeps;image/x-gzeps;image/vnd.djvu+multipage;image/tiff;
```

So offering the Document Viewer is not unsuitable for TIFF files. However, Photos offers the same app list for various formats, so when the opened file is not TIFF files, it's not suitable.
