### ISSUE TITLE
Info sidebar not usable when opening image directly

### ISSUE THREAD

**Issue by cristianofmc** [elementary/photos#463]
I tried to search and I could not, I think it's something quite simple and very useful.

**Comment by marco4mp** [comment]
Maybe it refers to [(https://github.com/elementary/photos/issues/481#issue-393630362)](url)

**Comment by marco4mp** [comment]
Maybe it refers to [https://github.com/elementary/photos/issues/481](url)

**Comment by marco4mp** [comment]
Maybe it refers to [https://github.com/elementary/photos/issues/481]

**Comment by cassidyjames** [comment]
@marco4mp ah you're probably right. I'll close that as a duplicate of this and add details.

**Comment by danrabbit** [comment]
This seems to be a duplicate of #277
