### ISSUE TITLE
libgexiv2 0.11 breaks build

### ISSUE THREAD

**Issue by decathorpe** [elementary/photos#484]
Building photos (both the latest stable release and git master) against libgexiv2 0.11 currently fails with the following error:

```
../src/photos/PhotoMetadata.vala:177.9-177.39: error: 1 extra arguments for `bool GExiv2.Metadata.open_buf (uint8[])'
        exiv2.open_buf (buffer, length);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/photos/PhotoMetadata.vala:191.9-191.48: error: 1 extra arguments for `bool GExiv2.Metadata.from_app1_segment (uint8[])'
        exiv2.from_app1_segment (buffer, length);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It looks like the API changed when the version was bumped from 0.10.10 to 0.11.0 (or something's broken in the VAPI file).

**Comment by decathorpe** [comment]
I've also reported this to `gexiv2` upstream, because this is possibly caused to an error in the VAPI file. https://gitlab.gnome.org/GNOME/gexiv2/issues/39

**Comment by phako** [comment]
This change was sent in by Corentin some time ago. I did not take it in for 0.10.x stable series but it is now in 0.11.x unstable which will become 0.12.0 stable next week

**Comment by decathorpe** [comment]
@phako Thanks for clarifying. Looks like this has to be fixed in photos, after all.

For reference:
https://gitlab.gnome.org/GNOME/gexiv2/commit/53c08bf2e4eacd438e822c305541c0de0ee2f74a

**Comment by decathorpe** [comment]
@tintou ↑

**Comment by worldofpeace** [comment]
This is still broken with the same problem in 0.12.

ping @tintou
