### ISSUE TITLE
flexible database location

### ISSUE THREAD

**Issue by snowparrot** [elementary/photos#485]
Like in Notes-Up it is very comfortable, if you can change the database location via gconf.

1.) you can easily backup. (TBH it is not documented where my database is)
2.) It is easier to develop photos if you can change the database.

**Comment by tintou** [comment]
I'm very -1 on this, it doesn't help to backup the db and developers should be able to deal with the database themselves.

**Comment by snowparrot** [comment]
It does help very much to backup as you can move the database to a cloud (e.g. nextcloud).

**Comment by tintou** [comment]
> It does help very much to backup as you can move the database to a cloud (e.g. nextcloud).

No, you don't want to do this, really

**Comment by snowparrot** [comment]
Wow thank you. This was a very friendly and nice answer.

**Comment by tintou** [comment]
Sorry but this is a bad idea to use a cloud folder to store a database that is only here to cache locally the content of folders. It's also not a good idea to have several parts of the system modifying the database (the sync daemon + Photos) and can leads to undefined behaviors.
So while having a backup of your data is good, but pointing directly to the backup is not the good way to do it.
