### ISSUE TITLE
Use FileChooserNative

### ISSUE THREAD

**Issue by danrabbit** [elementary/photos#488]
- [x] https://github.com/elementary/photos/blob/3dfa73156dc7d2e5f50a133f8d91a385570639e5/src/Dialogs/Dialogs.vala#L92
- [x] https://github.com/elementary/photos/blob/3dfa73156dc7d2e5f50a133f8d91a385570639e5/src/Dialogs/Dialogs.vala#L121
- [x] https://github.com/elementary/photos/blob/43bff10b9228814d07b54637e5b6961f02893221/src/Views/DirectPhotoPage.vala#L415
- [x] https://github.com/elementary/photos/blob/cc0512b046216521d7279222c74c6610ceb4aa9f/src/library/LibraryWindow.vala#L615

**Comment by peteruithoven** [comment]
These all seem switched to native. 

@danrabbit why not include the following one?
https://github.com/elementary/photos/blob/master/src/Dialogs/Dialogs.vala#L607
