### ISSUE TITLE
Sorting issues

### ISSUE THREAD

**Issue by zelikos** [elementary/photos#501]
Sorting photos by title works as expected, however sorting by exposure date has problems.

1) The "exposure date" it reads seems to be the date the picture was last modified, rather than when it was actually created.

2) It doesn't properly sort by date, anyway:
![Screenshot from 2019-04-05 20-39-02_modified](https://user-images.githubusercontent.com/26857149/55662617-261ae400-57e3-11e9-8309-400147de31ea.png)

In the above screenshot, my pictures are sorted by exposure date, in *ascending* order, but more *recent* pictures are near the top, and only some of them are in the correct order.

**Comment by justledbetter** [comment]
I'm working on a sort-of fix for this - by adding an option to sort by "File Modification Date".  Getting ready to submit a pull request to see if the Dev team likes it.
