### ISSUE TITLE
Crashes when auto-importing from large library of images

### ISSUE THREAD

**Issue by KeironO** [elementary/photos#507]
I love this application, but whenever I want to move my photos over it seemingly crashes when "auto importing".

```


** (io.elementary.photos:5455): WARNING **: 17:02:49.337: BatchImport.vala:1831: Unable to perform MD5 checksum on file /media/keo7/500GBWDB/Pictures/2019/23/_MG_3119.CR2: Error opening file /media/keo7/500GBWDB/Pictures/2019/23/_MG_3119.CR2: No such file or directory

** (io.elementary.photos:5455): WARNING **: 17:02:49.337: BatchImport.vala:1399: Import failure /media/keo7/500GBWDB/Pictures/2019/23/_MG_3119.CR2: File error

** (io.elementary.photos:5455): WARNING **: 17:02:51.948: Exif tag Exif.Photo.MakerNote not encoded


** (io.elementary.photos:5455): WARNING **: 17:02:51.949: Exif tag Exif.Canon.0x4002 not encoded


** (io.elementary.photos:5455): WARNING **: 17:02:51.949: Exif tag Exif.Canon.0x4005 not encoded


** (io.elementary.photos:5455): WARNING **: 17:02:53.890: Exif tag Exif.NikonPreview.JPEGInterchangeFormatLength not encoded


** (io.elementary.photos:5455): WARNING **: 17:02:53.890: Exif IFD NikonPreview not encoded


** (io.elementary.photos:5455): WARNING **: 17:02:53.890: Exif tag Exif.Photo.MakerNote not encoded


** (io.elementary.photos:5455): WARNING **: 17:03:02.635: Exif tag Exif.NikonPreview.JPEGInterchangeFormatLength not encoded


** (io.elementary.photos:5455): WARNING **: 17:03:02.635: Exif IFD NikonPreview not encoded


** (io.elementary.photos:5455): WARNING **: 17:03:02.635: Exif tag Exif.Photo.MakerNote not encoded


** (io.elementary.photos:5455): WARNING **: 17:03:05.949: Exif tag Exif.Photo.MakerNote not encoded


** (io.elementary.photos:5455): WARNING **: 17:03:05.949: Exif tag Exif.Canon.0x4002 not encoded


** (io.elementary.photos:5455): WARNING **: 17:03:05.949: Exif tag Exif.Canon.0x4005 not encoded


```

**Comment by panicsteve** [comment]
I'm not sure if I'm having this same bug, or just a similar one, but I'm adding my anecdote just in case.

I copied an export of the Photos Library from my Mac to ~/Pictures on my Elementary computer.  This is a big library.  It's about 100 GB of JPEGs, MOVs, HEICs, HEIFs, and maybe other formats.  (This is part of a larger experiment to see if it's feasible for me to bring all my Mac stuff over to Elementary and "live" there.)

Upon starting Photos, it began "auto-importing" but has crashed several times during this process if I attempt to interact too much with the app while it's importing.  (I would share the crash log, but I don't know where it lives, and there was no option to report the crash upon restarting the app -- it just silently quit.  Happy to share the log if someone can tell me where to find it!)

On my current attempt, leaving the app alone during import to avoid crashes, the auto-importing phase has reached 47% but has not increased for at least an hour.  It's using over 100% CPU and my laptop fans are going full blast.  I'll let it continue doing its thing for a while and see what happens.

**Comment by ckieling85** [comment]
Hey guys, are you still having this problem? I have a clean installation of Elementary OS 5.1 and I just copied over 30gb of images to the "Images" folder but when I open Photos, the program closes by itself as it starts importing automatically.

**Comment by KeironO** [comment]
@ckieling85

> Hey guys, are you still having this problem?

Yep, it still crashes. I've stopped using Photos, instead opting to use DarkTable and a fairly convoluted folder structure for image management.

**Comment by Pocker-Alho** [comment]
Hello,

The problem still persists on Elementary Odin (latest version, 2021). I posted a video of it on Elementary Twitter: https://twitter.com/AloneInThePark1/status/1426291957811253252

A bug from 2019, it seems.

**Comment by Poker-Alho** [comment]
Hello,

The problem was solved, at least for me, with their last updates (this week?). You should all try it, now.

**Comment by jeremypw** [comment]
Closing as incomplete as it is uncertain whether this issue still occurs with the latest version and what kind of file causes it.  Please feel free to re-open if it still occurs and it is not already covered by a more recent report.
