### ISSUE TITLE
Print screen is taken from Gnome

### ISSUE THREAD

**Issue by D0J0P** [elementary/photos#515]
The UI for the current print screen from elementary's Photos app is taken from Gnome and is not native to elementary and it's HIG.

Photos:
![Screenshot from 2019-07-30 22 30 58](https://user-images.githubusercontent.com/19495660/62179248-dcb64d80-b319-11e9-881b-4db4119a302c.png)

Gnome's Shotwell:
![Screenshot from 2019-07-30 22 33 23](https://user-images.githubusercontent.com/19495660/62179304-10917300-b31a-11e9-8e2c-d39326feac60.png)

This screen also appears when you open a photo from Files, right-click > Other Actions > Print...

**Comment by cassidyjames** [comment]
This is actually the GTK print dialog, not specifically for GNOME. I don't think printing is such a high priority that we'd spend the time creating our own just for a handful of apps, so I'm inclined to close this as out of scope.

**Comment by D0J0P** [comment]
Maybe just set it to low priority? It would definitely make sense if every bit of every app shipped with eOS fit into it's HIG completely, but I agree its not an urgent matter, just something that would be nice to have if someone happened to have time to clean it up and align it with the HIG.
