### ISSUE TITLE
Compress window is white

### ISSUE THREAD

**Issue by D0J0P** [elementary/photos#518]
Right click on photo > Other Actions > Compress
![Screenshot from 2019-07-30 23 16 40](https://user-images.githubusercontent.com/19495660/62181162-6406bf80-b320-11e9-9df7-bdaf31fc3878.png)
Also, clicking on the Location selection field, you'll see Desktop has no icon like the rest. 

This window shows up the same way in the photo viewer in files.

**Comment by cassidyjames** [comment]
I'm guessing this window is provided by File Roller via Contractor… hm. Since it's not technically part of Photos, I'm not sure how to solve this one.

**Comment by danrabbit** [comment]
Yeah I think this is working as intended since you’re launching another app. The same as it would be if you launched a mail compose window. Nothing really to be done here
