### ISSUE TITLE
Revert to Original dialog doesn't follow HIG

### ISSUE THREAD

**Issue by D0J0P** [elementary/photos#519]
Just like [#812](https://github.com/elementary/files/issues/812), Photos' Revert to Original dialog(right click on photo > Revert to Original) doesn't look right with the spacing of the buttons at the bottom. 
![Screenshot from 2019-07-30 23 44 19](https://user-images.githubusercontent.com/19495660/62182341-46d3f000-b324-11e9-9f08-2476f07b9b4e.png)

**Comment by ryonakano** [comment]
The PR #502 should fix this.

**Comment by ryonakano** [comment]
Fixed in #502.
