### ISSUE TITLE
Viewing image files on the Desktop via Spacebar

### ISSUE THREAD

**Issue by a-tokarev** [elementary/photos#536]
Currently, Photos allows viewing images via Spacebar only from Files browser. All image files on the Desktop can't be viewed via Spacebar and require double-clicking. Which is a) longer and b) inconsistent compared to Files.

**Feature request:** in addition to double-clicking, allow Photos to view image files on the Desktop via Spacebar key (just like in Files).

**Comment by cassidyjames** [comment]
@a-tokarev What do you mean by the desktop? Are you using elementary OS? Photos does not control any desktop behavior—that would be controlled by whatever is putting icons on the desktop for you, and on elementary OS, that doesn't exist.

**Comment by a-tokarev** [comment]
By the Desktop I mean https://github.com/spheras/desktopfolder - the only means to keep files on my screen, while working in elementary OS (yes, I'm using elementary OS.). Based on your reply, I'm guessing, what doesn't officially exist on elementary OS, couldn't be fixed. If so - sorry, I must have knocked the wrong door.

**Comment by danrabbit** [comment]
Closing since this seems to be an issue with spheras/desktopfolder

**Comment by cassidyjames** [comment]
@a-tokarev as a further note, neither the Files app nor Photos do anything special with spacebar, it simply opens the focused file. And since Photos is the default handler for image files, it just opens it up. If Desktop Folder were to add the ability to open focused images with the spacebar, it should all just work.

**Comment by a-tokarev** [comment]
@cassidyjames yes, I got it. Feature request re-addressed to 'Desktop Folder' devs.
