### ISSUE TITLE
Unmet Dependencies while installing photos from AppCenter

### ISSUE THREAD

**Issue by joe247** [elementary/photos#538]
> There Was An Error Installing Photos.
The following packages have unmet dependencies: pantheon-photos-common: Depends: pantheon-photos but it is not going to be installed

How can I fix it?

**Comment by JARVIS-AI** [comment]
Duplicate One [#458](https://github.com/elementary/photos/issues/458)
Duplicate Two [#478](https://github.com/elementary/photos/issues/478)

Please search before make another issue
Still Not Fixed [Juno]
