### ISSUE TITLE
All Images stay when going through Library

### ISSUE THREAD

**Issue by AtjonTV** [elementary/photos#543]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
After the Update to 2.6.5 when I go though images, the prior image is not cleared out and just stays.

### To Reproduce
1. Open Photos
2. Select Folder/Libaray
3. Press Left and Right arrow buttons

### Expected behavior
When I go to a new Image, the prior one should dissapear.

### Screenshots or screen recordings

WebM Video: https://cloud.atvg-studios.com/index.php/s/mxbkKJStiW3mtWr

### Logs
(No erros in the log)

## Platform Information
![image](https://user-images.githubusercontent.com/24845056/70267055-f3742180-179d-11ea-95db-4e1f4875966e.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by danrabbit** [comment]
When using unsupported CSS you should expect to encounter visual glitches like this. The issue does not occur when using the default system stylesheet.

**Comment by AtjonTV** [comment]
The only question I have is, why did it work before then?

I use this stylesheet since ElementaryOS 0.4.1 and I never had this issue in Photos. Only since the latest update of Photos.

I did not change the stylesheet since installation of the system over a year ago.
