### ISSUE TITLE
Launched via Files, browsing doesn't clear app window between image draws

### ISSUE THREAD

**Issue by reece146** [elementary/photos#544]
I went through a few pages of open issues to see if this was already posted - apologies if I missed it.

Hoping I can explain this clearly...

When browsing a directory of images in Files, and then double clicking an image, Photos launches as expected.

But, then navigating from file to file within Photos via the bottom left arrow buttons or keyboard arrow keys the window between images is not "reset" before the next image is displayed. The image is directly overlaid on the already existing image. I grabbed some random images off Twitter to show the issue in app screen shots.

![Screenshot from 2019-12-13 18-09-51](https://user-images.githubusercontent.com/6394378/70838111-b5e24a80-1dd4-11ea-83e5-0596adae339c.png)

You can see there are images under the red Lancia-Ferrari. This occurred by arrowing through the files in the directory.

Two more button presses and the images are overlaid the red car and looks like this:

![Screenshot from 2019-12-13 18-10-40](https://user-images.githubusercontent.com/6394378/70838152-e75b1600-1dd4-11ea-92f1-d3502b93cee7.png)

I'm running 5.1, updated a few days ago. I noticed this started a few weeks ago (sorry - no more precise than that)  but in the past it has worked as expected (i.e. app window cleared before next image drawn).

Thanks for your attention.

**Comment by jeremypw** [comment]
Could not reproduce this with updated Juno unstable (which should be equivalent to Hera).  I tried with both single-click (default) activation and double-click activation.  I'll try a clean install of Hera iso.

**Comment by jeremypw** [comment]
Could not reproduce on a clean Hera install either.  Maybe something to do with window manager (Gala) and/or video driver (I have NVidia GeForce MX150)

**Comment by cassidyjames** [comment]
It looks like the report is using a non-default system stylesheet. My guess is it does not have the required styling for checkerboard backgrounds, meaning the stylesheet is not properly drawing the background of the image view.

**Comment by reece146** [comment]
Ah! That was exactly the problem!

Thanks!
