### ISSUE TITLE
User-friendly tagging

### ISSUE THREAD

**Issue by epe** [elementary/photos#549]
Having used digikam ages ago, it seems like a throwback of 15 years to use the photos application in elementary. 

Digikam did everything right, what you need to tag a lot amount of photos rather quickly: 
- drag&drop UI where you can drop one or several files to the tag in a list of tags
- tree view of tags, where you can organise your tags (see below), and open/collapse a part of the tree.

region/austria
region/france
event/this
event/that
Cycling/
cycling/urban
cycling/cargo
cycling/tandem
cycling/brands
cycling/brands/bakfiets
cycling/brands/bicicapici

....

**Comment by jeremypw** [comment]
Photos now has drag and drop onto tags and hierarchical tags.  Closing as the no other specific changes were mentioned.
