### ISSUE TITLE
Some shortcuts no longer works

### ISSUE THREAD

**Issue by ryonakano** [elementary/photos#600]
## What Happened

Some shortcuts like Left to view previous photo, Right to view next photo, etc. no longer works after 2f59ff0e60cfe6311e085b6abb9d9de09d94c689.

## Expected Behavior

All shortcuts should work as expected.

## Steps to Reproduce

1. Build and install 5dde81016a62e00dcef5187ad6018a8a35b7c314 which is the parent commit of 2f59ff0e60cfe6311e085b6abb9d9de09d94c689
2. Open some photo from Files. Image Viewer opens
3. Press Right/Left key. Images cycles.
4. Build and install 2f59ff0e60cfe6311e085b6abb9d9de09d94c689
5. Open some photo from Files. Image Viewer opens
6. Press Right/Left key. Images do not cycle.

### Logs

```
** (io.elementary.photos:15336): WARNING **: 13:08:55.244: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action PrevPhoto

** (io.elementary.photos:15336): WARNING **: 13:08:55.244: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action NextPhoto

** (io.elementary.photos:15336): WARNING **: 13:08:55.244: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action FlipHorizontally

** (io.elementary.photos:15336): WARNING **: 13:08:55.244: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action FlipVertically

** (io.elementary.photos:15336): WARNING **: 13:08:55.244: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action SetBackground

** (io.elementary.photos:15336): WARNING **: 13:08:55.317: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action PrevPhoto

** (io.elementary.photos:15336): WARNING **: 13:08:55.317: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action NextPhoto

** (io.elementary.photos:15336): WARNING **: 13:08:55.317: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action FlipHorizontally

** (io.elementary.photos:15336): WARNING **: 13:08:55.317: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action FlipVertically

** (io.elementary.photos:15336): WARNING **: 13:08:55.317: Page.vala:256: Page Screenshot from 2021-02-04 13-05-31.png: Unable to locate action SetBackground
```

## Platform Information

- elementary OS Odin Daily with fully updated
- Photos with latest master

**Comment by queeup** [comment]
If I click to photo once with pointer then it works.

**Comment by queeup** [comment]
App is focusing "Save as" icon on the top. I think that's why Right/Left key not working for navigate.

![focus_bug](https://user-images.githubusercontent.com/87835/129458079-5a4fa097-6abd-4e1a-968c-479f6aea8f3e.png)
