### ISSUE TITLE
App crashes while importing photos

### ISSUE THREAD

**Issue by ghost** [elementary/photos#653]
### What Happened?

Hello, I have a huge library (33 gb) of photos and videos and after importing some of them (~70%) this app crashes. This is happening on a clean install of eOS 6. I am new to Linux and Github in general so I don't know what I am supposed to do. 

### Steps to Reproduce

1. Import a lot of photos and videos.
2. And it crashes immediately. 

### Expected Behavior

It is supposed to open without hiccups. 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Yes Photos has diverged significantly from Shotwell by now and different bugs have been fixed in each.

**Comment by SperanzaAuslander** [comment]
I have no idea what was wrong but I solved my issue by importing photos in groups and I've found the jpeg file that was crashing the whole app -which is very very weird-. Anyway, I got rid of that photo and the problem solved.

**Comment by jeremypw** [comment]
If you can extract the metadata from the culprit image and post it here (or on the similar report) that would help diagnose the problem.  Photos should not crash even with pathological metadata.

**Comment by SperanzaAuslander** [comment]
Metadata Cleaner app from Flathub gives these results [https://imgur.com/a/F6afgnW](url). This picture was a screenshot from a video
