### ISSUE TITLE
Enable easier copying

### ISSUE THREAD

**Issue by undergroundwires** [elementary/photos#698]
### Problem

Copying image content is not so easy. I usually copy paste images to different websites.

### Proposal

1. "Copy to clipboard" item on right click menu
2. CTRL+C copies to clipboard automatically

**Comment by jeremypw** [comment]
This looks like a duplicate of #53.  It seems there is a draft PR linked to fix that issue (which I had forgotten about).

**Comment by undergroundwires** [comment]
Thanks for pointing out, sorry for missing it and taking your time.
