### ISSUE TITLE
Use Wallpaper Portal

### ISSUE THREAD

**Issue by danirabbit** [elementary/photos#753]
### Problem

We're currently relying on Contractor for setting the wallpaper, but we should be using the Wallpaper Portal

### Proposal

Use the Wallpaper Portal: https://valadoc.org/libportal/Xdp.Portal.set_wallpaper.html

**Comment by zeebok** [comment]
It seems like this would involve updating Contractor to not report this action from the call to `get_contracts_for_files()` or specifically looking for the wallpaper option and replacing it with the libportal version.

**Comment by danirabbit** [comment]
We're no longer shipping the set wallpaper contract with desktop settings, so this just needs a branch like https://github.com/elementary/files/pull/2432
