### ISSUE TITLE
Photo viewer isn't set as default for photos in OS 8

### ISSUE THREAD

**Issue by danirabbit** [elementary/photos#769]
### What Happened?

Photos viewer is no longer the default app for photos in OS 8

### Steps to Reproduce

1. Install a fresh daily of OS 8 after Photos was changed to Flatpak
2. launch a photo from Files
3. See the dialog for selecting a default app rather than the photo viewer

### Expected Behavior

Photo viewer should be the default app for image files

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
Additional info:

I tried using "Open with" → "Other Application…" and then opening with Photo Viewer, but then Photos launches, not Photo Viewer.

**Comment by danirabbit** [comment]
Okay so part of the problem is we need sandbox access for all of home to be able to open files: https://github.com/elementary/photos/pull/774

**Comment by vjr** [comment]
Why not just the Pictures folder inside home?

**Comment by danirabbit** [comment]
@vjr because then the viewer won't be able to open any files outside of Pictures :) This is probably ultimatetly a mistake in how Photos handles file opening tbh but this is the quick fix

**Comment by zeebok** [comment]
What pieces are left for this to be resolved exactly?

**Comment by danirabbit** [comment]
@zeebok If it hasn't been resolved by the latest release then we might just need to roll it back to being shipped in the Deb package for now. I haven't tested the latest daily to see if anything changed

**Comment by zeebok** [comment]
I tested a daily build in a VM and it still does not have Photo Viewer as the default app when I try and open a screenshot I take

**Comment by danirabbit** [comment]
Fixed in the latest daily :)
